name: Prepare Release
description: Creates a release branch and PR using semantic-release

inputs:
  github-token:
    description: GitHub token for authentication
    required: true
  commit-sha:
    description: Commit SHA to use for branch naming
    required: true

runs:
  using: composite
  steps:
    - name: Run Prepare Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      run: |
        # Create and checkout temporary branch with commit SHA
        TEMP_BRANCH="prepare/${{ inputs.commit-sha }}"
        git checkout -b "$TEMP_BRANCH"

        # Run semantic-release (updates files but doesn't commit)
        npx semantic-release --extends ./.releaserc/prepare.json

        # Check if semantic-release made any changes
        if git diff --quiet && git diff --cached --quiet; then
          echo "No release needed (no relevant changes)"
          exit 0
        fi

        # Get version and release notes from package.json
        VERSION=$(node -p "require('./package.json').version")

        # Commit the changes
        git add CHANGELOG.md package.json package-lock.json
        git commit -m "chore(release): $VERSION"

        # Rename branch to proper release branch name
        RELEASE_BRANCH="release/v$VERSION"
        git branch -M "$RELEASE_BRANCH"

        # Push branch
        git push --force-with-lease origin "$RELEASE_BRANCH"

        # Check if PR already exists
        PR_NUMBER=$(gh pr list --base main --head "$RELEASE_BRANCH" --json number --jq '.[0].number')

        COMMIT_TITLE=$(git log -1 --pretty=%s)
        COMMIT_BODY=$(git log -1 --pretty=%b)

        if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
          gh pr edit "$PR_NUMBER" --title "$COMMIT_TITLE" --body "$COMMIT_BODY"
          echo "Updated existing PR #$PR_NUMBER"
        else
          gh pr create --base main --head "$RELEASE_BRANCH" --fill
          echo "Created PR for v$VERSION"
        fi
